[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/*',
    'client/offchain-ipfs-client',
    'runtime',
    'contracts/uniswap_v2',
    'offchain-ipfs-primitives'
]
