
//! Autogenerated weights for pallet_polkapool
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-14, STEPS: `[20, ]`, REPEAT: 30, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/polkadex-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 20
// --repeat
// 30
// --raw
// --output
// ./benchmarking


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_polkapool.
pub trait WeightInfo {
    fn claim_feeless_transaction() -> Weight;
    fn unstake() -> Weight;
    fn slash_stake() -> Weight;
}


/// Weight functions for pallet_polkapool.
pub struct PalletWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeightInfo<T> {
    fn claim_feeless_transaction() -> Weight {
        (64_571_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
    }
    fn unstake() -> Weight {
        (26_601_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
    }
    fn slash_stake() -> Weight {
        (44_924_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}
