
//! Autogenerated weights for polkadex_fungible_assets
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-07-14, STEPS: `[20, ]`, REPEAT: 30, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/polkadex-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 20
// --repeat
// 30
// --raw
// --output
// ./benchmarking


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;


pub trait WeightInfo {
    fn create_token() -> Weight;
    fn set_vesting_info() -> Weight;
    fn claim_vesting() -> Weight;
    fn mint_fungible() -> Weight;
    fn burn_fungible() -> Weight;
    fn attest_token() -> Weight;
    fn modify_token_deposit_amount() -> Weight;
    fn set_metadata_fungible() -> Weight;
}

/// Weight functions for polkadex_fungible_assets.
pub struct PalletWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeightInfo<T> {
    fn create_token() -> Weight {
        (39_675_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn set_vesting_info() -> Weight {
        (16_492_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn claim_vesting() -> Weight {
        (21_172_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn mint_fungible() -> Weight {
        (38_022_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn burn_fungible() -> Weight {
        (21_158_074_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn attest_token() -> Weight {
        (29_004_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    fn modify_token_deposit_amount() -> Weight {
        (18_839_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }

    fn set_metadata_fungible() -> Weight {
        (36_351_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
}
